### ISSUE TITLE
Bug: Player collisions dragging other players around

### ISSUE THREAD

**Issue by Cablefish1** [jonathaneeckhout/jdungeon#103]
In certain circumstances a player can drag other players around by bumping into them in the right circumstances. I don't know excactly what happens but if two players click walk into each other a lot it is bound to happen again. More testing required.

**Comment by NancokPS2** [comment]
I am unsure if we need player-to-player collision at all tbh.

**Comment by jonathaneeckhout** [comment]
Valid point, we don't need player-to-player collision

**Comment by NancokPS2** [comment]
Ready to be closed i think
