### ISSUE TITLE
Dev Task: Abstract Shared Enemy Code

### ISSUE THREAD

**Issue by ivoryfitz** [jonathaneeckhout/jdungeon#111]
Currently, the three enemies we have (Sheep, MoldedDruvar, TreeTrunkGuy) share a LOT of code between them. We should be able to abstract this and should do so now that we've hit the "rule of three".

I'm torn on if you should just add the shared code directly to `JEnemy2D` or if we should extend it and make a new class. I think the right call is to just put the shared code in JEnemy2D, but open to suggestions.

**Comment by ivoryfitz** [comment]
Addendum: Also update NPC  (milklady) to use the shared AI code and finish ripping out the old behavior scripts/setup.

**Comment by jonathaneeckhout** [comment]
Closing this one as most of the enemy code is now shared with the component system
