### ISSUE TITLE
Dev task: Add option to respawn at the nearest safe point

### ISSUE THREAD

**Issue by NancokPS2** [jonathaneeckhout/jdungeon#125]
Necessary to get players unstuck for whatever reason. Probably a nice QoL feature too.  
If we want to encourage more walking we can always give it a long arming time.

**Comment by jonathaneeckhout** [comment]
This can be achieved by opening the menu and press the "I'm Stuck Help!" button. This will kill the player and you will respawn at the nearest respawn location.
