### ISSUE TITLE
Documentation: High level explanation of server/client architecture

### ISSUE THREAD

**Issue by hortinstein** [jonathaneeckhout/jdungeon#126]
First of all, I am so excited to find this project, this is exactly what I was looking for as my next step on learning godot.

Recommend adding to the main page a high level breakdown of how server and clients interact.  I am new to godot (and this is the first project I have looked at with networking), interested in contributing and spent some of yesterday going through the code to understand how it's all working.  I found most of the networking code, but don't quite understand what is being executed on the clients and servers.  

Here is what I have gleaned in my cursory explorations.  The server can be backed by JSON or postgres.  It's responsible for keeping track of all player actions and redistributing them to all the connected clients.  

Does the server also do all collision, physics stat counting etc?  Or do the clients have some role in that.  Is the server authoritative for all things?  How is interpolation handled?  Is the sync rate referenced similar to tick rate?

It would be helpful to also link to the Godot documentation on what libraries you are used. 

If I had a high level explanation to go off I would be happy to try and build some accompanying architecture diagrams to add to the project.  

Like I said before this project is incredible and your code is easy to follow even glancing through and it being the first real godot project I have read through besides the firebelley tutorial I am doing for a single player game on udemy.  I hope I can find some areas to contribute in soon.  Thanks for all your hard work and effort on this, would love to watch some YouTube videos if you ever put them out that talk about your development on this game!

**Comment by hortinstein** [comment]
For those looking for a good tutorial on Godot 4 networking: https://youtu.be/e0JLO_5UgQo?si=P5v1vcPKsZYSagQl

**Comment by hortinstein** [comment]
so this is in the handy links: https://github.com/jonathaneeckhout/jdungeon/wiki/Handy-Links#multiplayer going to close this now and maybe in future I will try to add some high level explanation to documents

**Comment by jonathaneeckhout** [comment]
Hey, thank you for your interest in this project.

Like you already mentioned a good start to understand how the network code works is to watch this youtube series:
https://www.youtube.com/watch?v=lnFN6YabFKg&list=PLZ-54sd-DMAKU8Neo5KsVmq8KtoDkfi4s 

To answer some questions:
- the server is authoritative, meaning that all collisions, actions, behaviors, ... are done on the server. The client is only responsible of providing input to the server and displaying it's current state towards the player.
- The server uses a database node to store the persistent (data that should stay over different sessions). Currently 2 backends are available: json -> easy for developing and running locally, postgress -> used on the deployed server
- Interpolation and extrapolation is handled here:
https://github.com/jonathaneeckhout/jdungeon/blob/main/scripts/components/positionsynchronizercomponent/PositionSynchronizerComponent.gd 
The client runs the game 100ms delayed from the server, the concept is described in these youtube videos:
https://www.youtube.com/watch?v=w2p0ugw3afs&list=PLZ-54sd-DMAKU8Neo5KsVmq8KtoDkfi4s&index=13
https://www.youtube.com/watch?v=XGyrKmOxLcc&list=PLZ-54sd-DMAKU8Neo5KsVmq8KtoDkfi4s&index=14

Feel free to contribute!

I hope this answers a subset of your questions.

Kind regards,
Mawakajaka

**Comment by hortinstein** [comment]
Thanks this is perfect!

**Comment by jonathaneeckhout** [comment]
Haven't tested it yet, I just followed the youtube tutorial. In this tutorial it is stated that 100ms is the industry standard. I can't verify that with real example but I believe the guy as it works fine in this project.
