### ISSUE TITLE
Bug: Player movement gets stuck when toggling backpack/equipment

### ISSUE THREAD

**Issue by ivoryfitz** [jonathaneeckhout/jdungeon#131]
I'm not 100% on the reproduction of this bug, but it happens when I open the "backpack" and try to move around, close it, move around. I'm not sure to the full order of operations, including a gif to show how I make it happen. Its something with opening backpack, equipping a weapon, then closing pack, trying to move, then you can't until you click on a new UI element or hit escape.

https://imgur.com/a/nAzNhYB

**Comment by jonathaneeckhout** [comment]
Haha, I like the gif, stress testing the behavior!

It sure looks like a bug!

**Comment by NancokPS2** [comment]
May just be JUI.above_ui not being properly set at some point.
