### ISSUE TITLE
Dev Task: add player respawn locations

### ISSUE THREAD

**Issue by jonathaneeckhout** [jonathaneeckhout/jdungeon#20]
When a player dies, a menu should pop up with the text "You died" and a counter should be displayed until respawned.

The player should respawn at the nearest respawn location.

**Comment by Noazs** [comment]
Hello, can i help with this issue?

**Comment by ivoryfitz** [comment]
Hey @Noazs! We'd love the contribution. Come join us on Discord and get some more information on it :)
https://discord.gg/8Urwbwgm

**Comment by jonathaneeckhout** [comment]
Hey @Noazs you can certainly help with this. Like @ivoryfitz said, feel free to join the discord server for more information/help.

**Comment by jonathaneeckhout** [comment]
How are things going? Need any help?

**Comment by Noazs** [comment]
Working on it, how do i set respawn point?

**Comment by jonathaneeckhout** [comment]
"Working on it, how do i set respawn point?" What do you mean?

Are you planning to make the front-end (thus some nice spot to respawn) or are planning to implement the back-end network logic or both?

**Comment by Noazs** [comment]
Bassicaly i have logic to respawn player on death in Player.gd, and i am gonna do UI pop up to show counter to respawn. I can make PR with it today or tommorow so someone can review it and tell me if its good or not.
