### ISSUE TITLE
Women and Men Character Equipment Support

### ISSUE THREAD

**Issue by WithinAmnesia** [jonathaneeckhout/jdungeon#240]
We need women and men players too. This can probably be done with swapping out the graphics but it needs a player selection option at the start. Also women need their own set of armour and equipment to match their body shape too. I am I did it where on Unreal with easyrpg that an the same equipment armour item can be equipped and the male gets male graphics and the female gets female graphics, they both had their own armour / equipment art sets that items could have like a check for it worked with new races in theory too for it was beyond just 2 choices but could be expanded endlessly if wanted. (From Discord).

**Comment by jonathaneeckhout** [comment]
Out of scope for this project or near future roadmap, closing this ticket
