### ISSUE TITLE
Creative Commons 0 / Public Doman Art Assets Options (Sprites and Graphics)?

### ISSUE THREAD

**Issue by WithinAmnesia** [jonathaneeckhout/jdungeon#241]
https://itch.io/c/1557879/lucifer
https://github.com/WithinAmnesia/ARPG/tree/main/C.C.0.%20Assets%20Archive/Art/FoozleCC/Lucifer
Creative Commons 0 / Public Domain Art ready to go. Its smaller dimensions easier more simple to make more assets; more accessible but still highly detailed. High creative efficiency workflow; low input, high output = more content with same amount of creative time, resources and energy.
https://github.com/WithinAmnesia/ARPG/blob/main/C.C.0.%20Assets%20Archive/Art/FoozleCC/Lucifer/Foozle_2DC0009_Lucifer_Warrior_Pixel_Art/Warrior%20Showreel.gif?raw=true
https://github.com/WithinAmnesia/ARPG/blob/main/C.C.0.%20Assets%20Archive/Art/FoozleCC/Lucifer/Foozle_2DC0011_Lucifer_Sorceress_Pixel_Art/Down/Png/SorceressDownRun.png?raw=true

Men and Women. I can art. I can convert these into the JDungeon format but these are 48x48 frames with ~32x32 sprites. JDungeon has 122-128x61-64 frames and ~96x32-36 sprites. JDungeon also uses 32x32 tiles and the Foozle / CC.0 Art also uses 32x32 tiles. 16x16 tiles offer more selection and accessibility and are compatible with 32x32 tiles (4x16x16 tiles = 1x32x32 tiles). Also this creates a Legend of Zelda A Link To The Past tile art effect for greater game play options where the player is larger than the map tiles. Which makes the area work feel more traversable and natural with WASD / directional movement. It feels smoother than blocky unnatural grid maps with 32x32 sprites and 16x16 tiles. Also it is easier to make giant sizes characters with larger dimension support with the main character sizes ~1 pixel = 60 mm.

I am wondering what it would take to do this conversion properly from a technical point of view (each body part is segment and the animation needs to link up properly). Also I am wondering how to expand the body customization so it at least on par but hopefully greater than World of Warcraft's equipment appearance system (more equipment / item slots that can be seen on the character). Head, Shoulders, Chest, Legs, Feet, Hands, Wrists, Waist, Back, Shirt, Tabard, Main Hand, Off Hand in what World of Warcraft Classic has for visual item appearances / equipment slots and I am hoping for more such as Pants, Socks, Face, Hat, Neck, Right Ring, Left Ring, Accessories, middle layer for Gambeson etc. well there are more slots and I can do the art for all of these yet I am wondering what the technical requirements for adding extra layers are to the character sprites. Feedback is welcome.

**Comment by WithinAmnesia** [comment]
[Item Level Armour.txt](https://github.com/jonathaneeckhout/jdungeon/files/14159895/Item.Level.Armour.txt)
[Armour Sets Metal (Mail and Plate) All Item Levels(~1-100)(Extrapolated)++.txt](https://github.com/jonathaneeckhout/jdungeon/files/14159922/Armour.Sets.Metal.Mail.and.Plate.All.Item.Levels.1-100.Extrapolated.%2B%2B.txt)
[types.txt](https://github.com/jonathaneeckhout/jdungeon/files/14159940/types.txt)
This is what I had implemented in Flare for character equipment item slots: https://github.com/flareteam/flare-game/discussions/935
"Equipment types

Arms:

Main Hand
Off Hand

Main Armour:

Head
Torso
Waist
Legs
Shins
Feet
Shoulders
Arms
Wrists
Hands

Clothing / Unarmoured:

Hat
Eyes
Face
Neck
Amulet
Back
Tabard
Shirt
Gloves
Girdle
Pants
Socks
Finger
Trinket
Accessory

Enhancements:

Aura Enhancement
Armour Enhancement
Weapon Enhancement

Carried types (placeholders):

Consumable
Gem
Key
Book
Ancient Relic
Crafting Resource
Crafting Tool

-Matthew Gordon Roulston 9:15 PM 30th / 05 (May) / 2021"

**Comment by WithinAmnesia** [comment]
[inventory.txt](https://github.com/jonathaneeckhout/jdungeon/files/14160007/inventory.txt)
Also here is the Flare character equipment inventory that I implemented. I like Flare a lot but people need networking but I made 4K resolution graphics from 480p original resolution with Flare. I'll have to work with JDungeon and Godot 4.NET to to save my work and since JDungeon is an MMORPG at the core I will try to Godot-ify my WoW and BG / Diablo work and projects too or take what I reasonably can too hopefully. I got a lot of work with converting old work from 6-10+ engines / games / RPGs into Godot 4.NET JDungeon file / data formats. Lots needs to be expanded bit by bit.

**Comment by jonathaneeckhout** [comment]
Great ideas for new assets but make sure that the new assets match the current "art style". We tried to describe the style here:
https://github.com/jonathaneeckhout/jdungeon/wiki/F.A.Q.-(Frequently-Asked-Questions)#what-is-the-art-style-for-the-game-how-can-i-contribute

**Comment by jonathaneeckhout** [comment]
Out of scope for this project or near future roadmap, closing this ticket
