### ISSUE TITLE
Looking for help with adding visual equipment slots 

### ISSUE THREAD

**Issue by WithinAmnesia** [jonathaneeckhout/jdungeon#242]
https://github.com/jonathaneeckhout/jdungeon/issues/241#issuecomment-1926145522

May I get some help adding equipment slot types with JDungeon to implement added for visual character equipment slot art with?
"Arms:

Main Hand
Off Hand

Main Armour:

Head
Torso
Waist
Legs
Shins
Feet
Shoulders
Arms
Wrists
Hands

Clothing / Unarmoured:

Hat
Eyes
Face
Neck
Amulet
Back
Tabard
Shirt
Gloves
Girdle
Pants
Socks
Finger
Trinket
Accessory"

I want to make all the art for male and female humanoids ~2 meters / ~6 feet in height / 32x32 sprites with the above item slot layer but I need support in adding the technical ability for JDungeon to handle so many stacking visual equipment layers. There are working equipment / character art layers I am curious who can / wants to help guide myself to add these new visual character equipment slots? It seems since its 2D the character can have simple stacking equipment layers. I did this with 3D 8K textures on male and female compatible equipment on metahumans rigged and implemented for EasyRPG in Unreal 5 and it was very hard on the computers but we have 2D art so it should be way nicer on the computers lol. Also how do we add in the 4 (maybe 8) animation directions to sprites so it looks like a proper 2D MMORPG?

**Comment by WithinAmnesia** [comment]
I helped myself for sprites and rendering (240x432p-4K)!
![A R P G  JDungeon Godot 4 NET V 000 002-3 Big Rendering Success 240x432p-4K !](https://github.com/jonathaneeckhout/jdungeon/assets/86871191/88a6c34d-04bd-4bad-9eb4-606de6b30f72)

**Comment by jonathaneeckhout** [comment]
Do you still need help with this one?

If yes, you can reopen it.

**Comment by WithinAmnesia** [comment]
> Do you still need help with this one?
> 
> If yes, you can reopen it.

Kind of? But its okay closed. I have to do some tests anyway (to try and combine the traditional image sequences 4 to 8 directional movement animation frames with like 3-6 Godot 4.2.1.NET demos into JDungeon online webport version). Yet I would like to get help adding in more equipment for example additional layer slots like say how to add feet / boots would be a good starter.
