### ISSUE TITLE
Dev Task: Attack and Wander behavior

### ISSUE THREAD

**Issue by jonathaneeckhout** [jonathaneeckhout/jdungeon#25]
An enemy should wander around its spawn location.

Once a player gets too close to the enemy the enemy should go after the player and try to attack the player.

If the player runs out of range or is dead the enemy should return to wandering around its original spawn location.

**Comment by ivoryfitz** [comment]
I'm not sure how to "claim" this issue, but I'm actively working this fwiw :)

**Comment by ivoryfitz** [comment]
I think we can mark this one as completed/closed if you agree :)
