### ISSUE TITLE
How big can the maps be?

### ISSUE THREAD

**Issue by WithinAmnesia** [jonathaneeckhout/jdungeon#250]
Can we do ~1,048,576 square kilometers / ~1,024x1,024 maps x ~1,000x1,000 to 1,024x1,024 16x16 pixel tiles = ~60 mm per pixel?

What can the web browser handle and with how many players and with what kind of set up?

It's really fuzzy here and I would like to understand more if anyone is willing to help.

**Comment by jonathaneeckhout** [comment]
This explains how big maps can be:
https://github.com/jonathaneeckhout/jdungeon/wiki/Howto-make-new-map-chunks 

This was a draft I made of one shard:
![image](https://github.com/jonathaneeckhout/jdungeon/assets/44840503/633da786-f6ea-4216-a1bf-b8149aec4b9d)

**Comment by WithinAmnesia** [comment]
Can JDungeon map chunks be expanded 64 times so I can roughly match my previous scale of work with Flare (Diablo / Zelda open source engine) and if so I can roughly port over my prototypes from Flare and other game engines to Godot 4 relatively smoothly.

@jonathaneeckhout 128 x 128 areas with 32 x 32 pixel tiles = 16,777,216 square pixel chunks.

Can we do 1,024 x 1,024 areas with 16 x 16 pixel tiles = 268,435,456 square pixel chunks?

Or can this be made 16 times bigger per chunk reasonably?

In Flare I used 1,000 x 1,000 areas with 256 x 128 pixel isometric tiles for 32,768,000,000 268,435,456 square pixel areas.

Although in truth I should use my 32 x 32 sprite bases as tiles and ask can JDungeon handle 1,024 x 1,024 areas with with 32 x 32 pixel tiles = 1,073,741,824 square pixel chunks?

**Comment by jonathaneeckhout** [comment]
The 128x128 had been chosen to reduce the load on a single server. Increasing the size of the map exponentially increased the load. 

The size proposed is too large to be feasible with the current architecture.

**Comment by WithinAmnesia** [comment]
How is wow and minecraft hosted then? they are wayyyy bigger and 3D with more demanding networking too? why cant a 2D game try and test the limits like how much different is my request than say wow or minecraft but the characters are shrunk 16 times and the world feels 16 times larger?

**Comment by WithinAmnesia** [comment]
What are the server loads for x sizes anyway like what options are there?

**Comment by WithinAmnesia** [comment]
How can the server architecture be tested too? what options are there for testing and hosting? I can test locally but I should work with  server host too for the more realistic results. If I got the 4kx4k with 16x16 tiles area chunk going how can I test this with server hosting? What options are there? What would you recommend as some starting points?

**Comment by WithinAmnesia** [comment]
https://www.iamcal.com/articles/assets/wow_map_kalimdor.png here is an example of wow and its chunks
Also here is a map of osrs and it map chunks https://gitgeddes.github.io/ChunkPicker/ these are from the 2000's

**Comment by WithinAmnesia** [comment]
![image](https://github.com/jonathaneeckhout/jdungeon/assets/86871191/754b676b-5104-4f4f-b1a5-9c28a15d8783)
As like mate how can we do this?

**Comment by WithinAmnesia** [comment]
https://jonathaneeckhout.itch.io/jdungeon For the goal right now it is easy to play this but imagine it has seamless chunk loading and unloading. As instead of the black world boundary a new chunk loads in seamlessly. What are your suggestions and thoughts?

Update: https://github.com/WithinAmnesia/ARPG/tree/ARPG-Infinite-Worlds Here is the 128x128 with 32x32 pixel tile chunk to test.

My initial testing seems to feel even faster combat with the 128x128 chunk. This 128x128 chunk has the same amount of entities as the 256x256 chunk. For I moved all of the entities over into the 128x128 chunk. This 128x128 chunk is a good test for using the Infinite-Worlds using the BinarySerializer for Godot 4.2+ from Theraot: https://gist.github.com/theraot/31515e28e2d8bfea33f6c6d5bcd852f6 . There needs to be some testing how to make the chunks seamlessly load and unload.

I'm trying to find a way to seamless load and unload chunks for a 2D multiplayer game project to make an open world with a working server using Godot 4.2.1.NET. Example: https://www.youtube.com/watch?v=uE36MVjB5-8

How can this work for multiplayer and what is needed for this to potentially work? What options can be used for chunk loading and unloading seamlessly in Godot 4.2.1.NET? Please give feedback. Any help with the main proposal would help: https://github.com/godotengine/godot-proposals/issues/9108

Test chunks link: https://github.com/WithinAmnesia/ARPG/discussions/15

I have to keep track of these looking for help / related links:
https://gamedev.stackexchange.com/questions/209002/looking-for-help-godot-4-multiplayer-seamless-open-world-chunks
https://forum.godotengine.org/t/looking-for-help-godot-4-multiplayer-seamless-open-world-chunks/47902
https://github.com/WithinAmnesia/ARPG/discussions/ 15
https://github.com/godotengine/godot-docs/issues/8981
https://github.com/godotengine/godot-proposals/discussions/9109
https://jonathaneeckhout.itch.io/jdungeon
