### ISSUE TITLE
Classless / 4-6 Class Options, 16+ multiple characters per account / character selection screen / multiboxing features

### ISSUE THREAD

**Issue by WithinAmnesia** [jonathaneeckhout/jdungeon#252]
From Discord Suggestion.

Can we have a classless option like in osrs / oblivion too?
like maybe 4-6
adventurer (classless)
melee
ranged
caster
support
hybrid

Also can 1 account have a character selection screen like in wow / eq so we can have alts and not a billion passwords to keep track of like at least 16 characters if not like 100+ but like idk how we handle multiboxing I guess you have a feature like add alt to 1 client with ai / macros like rts / crpg like bg or iwd or d2 merc etc.
Also adding /follow /stop /hostile /defensive /passive /heal lowest ally commands (akin to bg / wow combat pet commands) would be massive for group / multiboxing / rts features.

**Comment by WithinAmnesia** [comment]
![A R P G  V 000 003-9 (JDungeon_Online_Webport) Godot 4 NET  Technically 14+2_16 Clients Multiboxing Does Work!](https://github.com/jonathaneeckhout/jdungeon/assets/86871191/59880922-c384-4126-916e-4e999fc7eefa)
1 computer has run 16 characters before its just if it was better integrated the experience would be better than 16 tab hoping. 16 is a natural number where it still does small things but it can do big things and also like chess its where most people can still keep track and it is a super divisible organization number 16->8->4->2->1. Its where it has RTS features but with the mental capability still within common expectations for most people to keep track of. This is an extra feature but it would be good for testing especially for dungeons / raids / player count activities. Even /follow /stop /hostile /defensive /passive /heal lowest ally commands (akin to bg / wow combat pet commands) would go so far with group / multiboxing / rts features.

**Comment by jonathaneeckhout** [comment]
Out of scope for this project or near future roadmap, closing this ticket
