### ISSUE TITLE
9+ Feature Requests (From ~Discord ~Internet)

### ISSUE THREAD

**Issue by WithinAmnesia** [jonathaneeckhout/jdungeon#254]
9+ Feature Requests (From ~Discord ~Internet):
1.) Can we have women and men gender selection and various appearance customization features per character?
2.) Can we have 1 account have a character selection screen like in wow / eq so we can have alts and not a billion passwords to keep track of like at least 16 characters if not like 100+? At least 16+ characters per account is ideal.
3.) Can we have an Adventurer (start with no features at the start) / 'default' / 'classless' class option like in osrs / oblivion?
4.) Can we have ~6 classes to pick at the start?:
- Adventurer (default / no features at the start / 'classless' / make your own class)
- Warrior (Melee dps / tank starter boost)
- Ranger / Wanderer (Ranged / bow dps starter boost)
- Wizard (Caster / dps starter boost)
- Warden / Cleric / Priest (Healer / support / dps start boost)
- Bard / Rogue / Worlder (Hybrid / dps / tank / healer jack of all trades boost)

5.) Can we have multiclassing like in BG3/D&D?
6.) Can we hotswap classes technically like in that demo you could selection 1 class load it up and play that with its own set of abilities can we bring that back as a hotswap to test things online? As like in the previous classes build demo press j to bring up class selection screen then swap to a class like ranger or caster to test abilities?
7.) Can we have classes that can just be titles and new classes can be changed into as options like unlocking new titles from hero orders and like D&D where classes can be added and changed later too? It makes it like legos for player choice and that's good for open source having those kinds of rpg options.
8.) Can we have multiboxing of up to 16 characters from 1 account on 1 client / player / computer like with bg3/infinity engine games/d2 merc/rts?
9.) Can we have /follow /stop /hostile /defensive /passive /heal_lowest_ally commands (akin to bg / wow combat pet commands) would go so far with group / multiboxing / rts features?
Bonus.) More Feature Requests:
Arbitrary Attributes, Arbitrary Resources (e.g. Health, Spirit, Mana etc.), Arbitrary Abilities, Groups, Raids, Instances, Guilds, Storage, Banking, Trade, Auction House, Mail Box System, Player / Guild Housing, Customizable Player Decorations / Tabards / Images / Armour / Weapons / Items / Appearances / Objects etc., Building, Tradeskills, Gather Skills, Crafting Skills, Skills minigames (e.g. weave stitches to sew item etc.), PvP, 'Single Player' / 'Personal Server' / 'Offline / Dev Mode', Mounts, Pets, LIGHT cosmetic only monetization and website store guide, Game Masters, Moderation and forums, Account Security, 'Vehicles' (e.g. siege tower, catapult, ship, hot air balloon, wagon, chariot, 'tank', 'air ship' etc.), public transportation (e.g. boats, wagons, trains, griffins etc.), sieges with destructible walls / gates (e.g wintergrasp in wow / mount and blade banner lord / lord of the rings / history). Barber shop to customize hair appearance etc. 2.5D graphics, 3D graphics VR, physics, realistic ballistics etc., summon avatars like D&D and conan mmorpg, dynamic spawning / populating world, music and play instruments like bg3/D&D, player feature voting polls for big time open source forever free MMORPGs!

Discord Requests Archived:

"Mawakajaka — Today at 02:28
what do you think of this class selection menu?

Cablefish — Today at 02:36
The Pick X in the bottom seems redundant

Mawakajaka — Today at 02:44
it's the actual button XD
[02:44]
but I understand your remark (edited)

Cablefish — Today at 04:59
I know. Just think the design could be neater someway

Matthew — Today at 08:37
can we have a classless option like in osrs / oblivion too?
[08:38]
like maybe 4-6
adventurer (classless)
melee
ranged
caster
support
hybrid
[08:41]
also can 1 account have a character selection screen like in wow / eq so we can have alts and not a billion passwords to keep track of like at least 16 characters if not like 100+ but like idk how we handle multiboxing I guess you have a feature like add alt to 1 client with ai / macros like rts / crpg like bg or iwd or d2 merc etc

Matthew — Today at 09:00
https://github.com/jonathaneeckhout/jdungeon/issues/252 I made it on github to better keep track of it. (edited)
GitHub
Classless / 4-6 Class Options, 16+ multiple characters per account ...
From Discord Suggestion. Can we have a classless option like in osrs / oblivion too? like maybe 4-6 adventurer (classless) melee ranged caster support hybrid Also can 1 account have a character sel...

@Matthew
https://github.com/jonathaneeckhout/jdungeon/issues/252 I made it on github to better keep track of it. (edited)

Nancok — Today at 18:42
Atm it would be easier to assign them the default class (which has no features) Since a lot of stuff REQUIRES the character to have a class to know how to define the stats.

But it wouldn't do anything other than making you play for a bit without any skills.
[18:42]
We can def. have multiple per account, but it would require a bit of a rework in how we store and load the data.
[18:44]
Also a reminder that characters can support ANY amount of classes, it is currently set to 1 in case new issues pop-up regarding multi-classing. That way we can focus on adding more features.
(Not like there's many options to multiclass towards rn) (edited)

Matthew — Today at 18:59
Hmmmm

@Nancok
Atm it would be easier to assign them the default class (which has no features) Since a lot of stuff REQUIRES the character to have a class to know how to define the stats. But it wouldn't do anything other than making you play for a bit without any skills.

Matthew — Today at 19:44
I just want a clean start by default (no features to start as you say) like osrs or oblivion where in oblivion you can pick a class that is a little boost to melee or range or caster or support or hybrid etc but with 'Adventurer' you get the option of build your own play style like osrs so if the default class was 'Adventurer' that started at a base default like a stem cell that could be further customized then we can have the best of both worlds. Also I hope classes can just be titles too and new classes can be changed into as options like unlocking new titles from hero orders and like D&D where classes can be added and changed 
later too. It makes it like legos for player choice and thats good for open source having those kinds of rpg options. (edited)

@Nancok
We can def. have multiple per account, but it would require a bit of a rework in how we store and load the data.

Matthew — Today at 19:46
at least characters 16+ per account is ideal

@Nancok
Also a reminder that characters can support ANY amount of classes, it is currently set to 1 in case new issues pop-up regarding multi-classing. That way we can focus on adding more features. (Not like there's many options to multiclass towards rn) (edited)

Matthew — Today at 19:49
can we hotswap classes technically like in that demo you could selection 1 class load it up and play that with its own set of abilities can we bring that back as a hotswap to test things online? like swap to 'adventurer' which is the base like a default thing (like you said has no features at the start) and like in the demo press j to bring up class selection screen then swap to a class like ranger or caster to test abilities?
[19:49]
Also multiclassing would be cool like in bg3/D&D (edited)
[19:52]
multiboxing is like bg3/infinity engine games/wow/eq/osrs where you control multiple characters with 1 client / pc / player. I had unreal easyrpg do this 3rd person 3D with 4k-8k metahumans with 16 party members multiboxing like bg3 or and rts kinda lol. I hope to be able to do so here so I can built big content like raids that work in multiplayer and single player and get bits of rts / crpg / bg3 type gameplay going."
-7:52 PM to 8:48 PM 13th / 02 (February) / 2024

Also inspired from:
https://github.com/jonathaneeckhout/jdungeon/issues/252
https://github.com/jonathaneeckhout/jdungeon/issues/244
https://github.com/jonathaneeckhout/jdungeon/issues/240
https://github.com/jonathaneeckhout/jdungeon/issues/238

Feedback is welcome!

**Comment by jonathaneeckhout** [comment]
Out of scope for this project or near future roadmap, closing this ticket
