### ISSUE TITLE
Everyone can try out the big 1,024 x 1,024 tiles with 32 x 32 pixel tile big chunk areas! [Feature Demonstration]

### ISSUE THREAD

**Issue by WithinAmnesia** [jonathaneeckhout/jdungeon#255]
https://github.com/WithinAmnesia/ARPG / https://github.com/WithinAmnesia/ARPG/tree/main/A.R.P.G.%20Godot%204%2B/A.R.P.G.%20V.000.007%20(JDungeon) The .zip file works now. I had to make a branch / use Github desktop to share the big are test. The proper accreditation is there too! It has bonus C.C.0 asset too. I am so happy that this worked. It is the first time I used Github desktop lol. Now everyone can try out the big 1,024 x 1,024 tiles with 32 x 32 pixel tile big chunk areas!

**Comment by jonathaneeckhout** [comment]
Out of scope for this project, closing this ticket
