### ISSUE TITLE
Error connecting to Gateway

### ISSUE THREAD

**Issue by warsang** [jonathaneeckhout/jdungeon#263]
Hi!

I get the following when trying to connect on itch[.]io:

<img width="355" alt="image" src="https://github.com/user-attachments/assets/1af1f0e2-1f20-4ea8-89e4-640f7c32d11c">

I'm guessing the server is currently down?

**Comment by jonathaneeckhout** [comment]
yes, I didn't renew the dns name so the certificate was not valid anymore. So I stopped the server.

You can still run it locally if you want to see it working.
