### ISSUE TITLE
Dev Task: create mushroom controlled lumberjack enemy

### ISSUE THREAD

**Issue by jonathaneeckhout** [jonathaneeckhout/jdungeon#32]
The forest is taking revenge on the lumberjacks who were cutting down the trees. Unknowingly by breathing in the spores of a puppet mushroom the lumberjacks lost control over their own body, eventually making them slaves of the mushroom. 

The lumberjacks should wander around in the Wakening forest.

**Comment by ivoryfitz** [comment]
I can take this issue.

Do we want the lumberjack AI to be the same as the TreeTrunkGuys?

**Comment by jonathaneeckhout** [comment]
I'd say yes, just slightly stronger? Maybe check with @NancokPS2 for the values?
