### ISSUE TITLE
Feature Request: Need a translation system.

### ISSUE THREAD

**Issue by NancokPS2** [jonathaneeckhout/jdungeon#58]
The built-in TranslationServer and a csv file are probably enough.

**Comment by jonathaneeckhout** [comment]
I am going to close this ticket as it's a nice idea but not in the scope of this project. I expect most of the players to be capable of understanding the basics of English. The game should not made too difficult to interact with that other languages cant understand what to do with it.

**Comment by jonathaneeckhout** [comment]
Nevermind, after reading this PR I understand the need for the translation file:
https://github.com/jonathaneeckhout/jdungeon/pull/65 

Make sure to properly document feature requests so that it's clear for what it is going to be used.

**Comment by NancokPS2** [comment]
> Nevermind, after reading this PR I understand the need for the translation file: #65
> 
> Make sure to properly document feature requests so that it's clear for what it is going to be used.

I only requested it because i know it is easy to do, anyone can make a translation file with a simple calc sheet editor (or just a text editor, for the brave)  
This also allows for easier localization in case someone wants to host their own server.

**Comment by jonathaneeckhout** [comment]
I am more pointing out to fill in the description why we need this feature. 

In this case one of the use cases would be:
- It allows easily mapping of internal input variable names to meaningful text for the end user. Example: j_toggle_bag can be easily mapped to: Toggle your Bag, which then can be used in the menu.

**Comment by jonathaneeckhout** [comment]
As it's clear why this could be useful I am converting this feature request to a dev task.
