### ISSUE TITLE
Feature Request: Client-side save system.

### ISSUE THREAD

**Issue by NancokPS2** [jonathaneeckhout/jdungeon#59]
This would be used for client-only data, like settings or some other client side preferences.    
Currently it is only planned for the settings menu.
Players could also be able to save infinite amounts of equipment presets (Payday 2 style) locally or something similar.

**Comment by jonathaneeckhout** [comment]
Please write down more information about this feature request.

What is it about, what are the use cases, what will it improve?

**Comment by NancokPS2** [comment]
Closed by #61
