### ISSUE TITLE
Dev Task: Flexible ability system

### ISSUE THREAD

**Issue by NancokPS2** [jonathaneeckhout/jdungeon#62]
We need an ability system that is fairly flexible in order to create more interesting abilities for characters. This would probably start with a rework of the stat system and how it is accessed.  
 
I'm honestly stumped so ANY idea on how to proceed would be great, how do other games do it?  
  
Some points on what would be ideally possible: https://docs.google.com/document/d/1S5PSdKvYGjjsThQ0EP7Ct3rSz1nKC3_3GmWJFCnVSh4/edit

**Comment by jonathaneeckhout** [comment]
I will put it for milestone 2. I don't think we will reach all skills by milestone 2 but this bug can at least provide information.

I've also put the information of the document into the wiki idea page:
https://github.com/jonathaneeckhout/jdungeon/wiki/Idea-Page#skills-nancok

**Comment by jonathaneeckhout** [comment]
@NancokPS2 what is the status of this issue?

I think this issue has a big overlap with what you're implementing in:
https://github.com/jonathaneeckhout/jdungeon/pull/188

**Comment by jonathaneeckhout** [comment]
> I will put it for milestone 2. I don't think we will reach all skills by milestone 2 but this bug can at least provide information.
> 
> I've also put the information of the document into the wiki idea page: https://github.com/jonathaneeckhout/jdungeon/wiki/Idea-Page#skills-nancok

Moving from milestone based project follow up to a project based follow up.

**Comment by NancokPS2** [comment]
> @NancokPS2 what is the status of this issue?
> 
> I think this issue has a big overlap with what you're implementing in: #188

This is basically done.  
Anything else would just be an expansion of the system.  
But skills are already as versatile (code-wise) as i could make them.
