### ISSUE TITLE
Feature Request: Debug actions/Console commands

### ISSUE THREAD

**Issue by NancokPS2** [jonathaneeckhout/jdungeon#64]
This would help a lot with testing. Just a way to call certain functions from in-game. Like a suicide command, set level, max gold, etc.

**Comment by jonathaneeckhout** [comment]
Setting parameters to a certain value can be done via the remote debug functionality of Godot. Also if you want to adjust the gold of a player you can modify the persistent file. I use it quite often.

**Comment by NancokPS2** [comment]
Good point, altho there's also the chance for server owners to simply tweak stuff without the need of the editor or simply cheat in their own environment.  
Altho that would turn this into a low priority, so i'll close it for now.
