### ISSUE TITLE
Bug: issues with jsonbackend

### ISSUE THREAD

**Issue by jonathaneeckhout** [jonathaneeckhout/jdungeon#85]
J.logger.err should be J.logger.error

https://github.com/jonathaneeckhout/jdungeon/blob/main/scripts/network/database/backends/JJSONDatabaseBackend.gd#L22

The USERS_FILEPATH should be an env variable, not a fixed location. This will mess up when the game is exported.

https://github.com/jonathaneeckhout/jdungeon/blob/main/scripts/singletons/jdungeon.gd#L18

**Comment by NancokPS2** [comment]
Not only there: https://github.com/search?q=repo%3Ajonathaneeckhout%2Fjdungeon%20err(&type=code  
  
Root.tscn also had "err(" at one point so it may be that the method was called like that originally.
